# fly.toml app configuration file generated for tall-stack-course-project on 2023-12-30T23:21:51+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "tall-stack-course-project"
console_command = "php /var/www/html/artisan tinker"
primary_region = "cdg"

[build]
[build.args]
NODE_VERSION = "18"
PHP_VERSION = "8.2"

[env]
APP_ENV = "production"
APP_URL = "https://tall-stack-course-project.fly.dev"
DB_CONNECTION = "pgsql"
LOG_CHANNEL = "stderr"
LOG_LEVEL = "info"
LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"
SESSION_DRIVER = "cookie"
SESSION_SECURE_COOKIE = "true"

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 8080
min_machines_running = 0
processes = ["app"]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 1024
